# Generated by Django 5.2.17 on 2026-08-29 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('web', 'Web'), ('app', 'App')], db_index=True, max_length=8)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=120)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=2048)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='core_errorl_source_78903a_idx')],
            },
        ),
    ]
