# Generated by Django 5.2.17 on 2026-09-09 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('operation', models.CharField(db_index=True, max_length=40)),
                ('model', models.CharField(db_index=True, max_length=60)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('audio_seconds', models.FloatField(blank=True, null=True)),
                ('input_chars', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', '-created_at'], name='core_modelu_operati_1b7c5e_idx'), models.Index(fields=['user', '-created_at'], name='core_modelu_user_id_64554a_idx')],
            },
        ),
    ]
