# Generated by Django 5.2.17 on 2026-08-29 13:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tidied_text', models.TextField(blank=True, default='')),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('original_transcript', models.TextField(blank=True, default='')),
                ('boosted_transcript', models.TextField(blank=True, default='')),
                ('gpt_transcript', models.TextField(blank=True, default='')),
                ('gpt_tidied_text', models.TextField(blank=True, default='')),
                ('duration', models.FloatField(default=0)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_processing', models.BooleanField(default=False)),
                ('is_refining', models.BooleanField(default=False)),
                ('is_polishing', models.BooleanField(default=False)),
                ('tidy_pending', models.BooleanField(default=False)),
                ('did_gpt_tidy', models.BooleanField(default=False)),
                ('did_gpt_transcribe_tidy', models.BooleanField(default=False)),
                ('processing_stage', models.CharField(blank=True, default='', max_length=120)),
                ('processing_log', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
